version: "3.9"

services:
  app:
    build: .
    container_name: props-app-crm
    ports:
      - "8040:8000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 8000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    networks:
      - props-network-crm

  db:
    image: mysql:8
    container_name: mysql-db-crm
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3316:3306"
    volumes:
      - crm_mysql_data:/var/lib/mysql
    networks:
      - props-network-crm

  redis:
    image: redis:7-alpine
    container_name: redis-crm
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - props-network-crm
    # ❌ نیازی به ports نیست (internal)

volumes:
  crm_mysql_data:
  redis_data:
  public_data:

networks:
  props-network-crm:
    driver: bridge
