version: "3.9"

services:
  app:
    build: .
    container_name: props-app
    ports:
      - "8040:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=my_props_strong@312@312
      - DB_NAME=props_db
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - public_data:/app/public  
    command: npm start
    networks:
      - props-network

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_props_strong@312@312
      MYSQL_DATABASE: props_db
      JWT_SECRET: dawdawfawf_adjaiwdhawihfmafa
    ports:
      - "3316:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - props-network

volumes:
  mysql_data:
  public_data:  

networks:
  props-network:
    driver: bridge
